export let productList = {  
    "Burgers": [
      { itemCode: "B1001", name: "Classic Burger", price: 1500.00, discount: 0, img: "../assets/images/Burger-Category/Classic Burger (Large).webp" },
      { itemCode: "B1002", name: "Turkey Burger", price: 1600.00,discount: 15, img: "../assets/images/Burger-Category/turkey-burger.png" },
      { itemCode: "B1003", name: "Chicken Burger", price: 1400.00,discount: 0, img: "../assets/images/Burger-Category/chicken-burger.webp" },
      { itemCode: "B1004", name: "Cheese Chicken Burger", price: 1000.00, discount: 5,img: "../assets/images/Burger-Category/cheese burger.webp" },
      { itemCode: "B1005", name: "Crispy Chicken Burger", price: 1200.00, discount: 0,img: "../assets/images/Burger-Category/Crispy Chicken Burger.webp"},
      { itemCode: "B1006", name: "Special Olive Burger", price: 1800.00, discount: 5,img: "../assets/images/Burger-Category/olive-burger.webp"},
      { itemCode: "B1007", name: "Bacon Burger", price: 650.00, discount: 0,img: "../assets/images/Burger-Category/becon-burger.webp" },
      { itemCode: "B1008", name: "Shawarma Burger", price: 800.00, discount: 12,img: "../assets/images/Burger-Category/shawarma-burger.webp"},
      { itemCode: "B1009", name: "Double Cheese Burger", price: 1250.00, discount: 20,img: "../assets/images/Burger-Category/Double-Cheese Burger.webp"},
      { itemCode: "B1010", name: "Paneer Burger", price: 900.00, discount: 0,img: "../assets/images/Burger-Category/Paneer Burger.webp"}
  ],
  "Submarines": [
      { itemCode: "B10011", name: "Double Cheese Chicken Submarine", price: 1900.00,discount: 16, img: "../assets/images/Submarine-Category/Double Cheese Chicken Submarine.webp"},
      { itemCode: "B10012", name: "MOS Special Submarine", price: 3000.00,discount: 0, img: "../assets/images/Submarine-Category/MOS Special Submarine.webp" },
      { itemCode: "B10013", name: "Special Horgie Submarine", price: 2300.00,discount: 0, img: "../assets/images/Submarine-Category/Special Horgie Submarine.webp"},
      { itemCode: "B10014", name: "Cheese Submarine", price: 2200.00,discount: 0, img: "../assets/images/Submarine-Category/Cheese Submarine.webp" },  
      { itemCode: "B10015", name: "Chicken Submarine", price: 2000.00,discount: 0, img: "../assets/images/Submarine-Category/chickensub.png" },
      { itemCode: "B10016", name: "Grinder Submarine", price: 2300.00,discount: 0, img: "../assets/images/Submarine-Category/Grinder Submarine.webp" },
      { itemCode: "B10017", name: "Crispy Chicken Submarine", price: 1500.00,discount: 0, img: "../assets/images/Submarine-Category/Crispy Chicken Submarine (Large).jpg" }
  ],
  "Pasta": [
      { itemCode: "B10018", name: "Chicken Cheese Pasta", price: 1600.00,discount: 15, img: "../assets/images/Pasta-Category/Chicken Chesese pasta.png" },
      { itemCode: "B10019", name: "Chicken Penne Pasta", price: 1700.00,discount: 0, img: "../assets/images/Pasta-Category/chicken panne.png" },
      { itemCode: "B10020", name: "Ground Turkey Pasta Bake", price: 2900.00,discount: 10, img: "../assets/images/Pasta-Category/Ground Turkey Pasta Bake.webp" },
      { itemCode: "B10021", name: "Creamy Shrimp Pasta", price: 2000.00,discount: 0, img: "../assets/images/Pasta-Category/Creamy Shrimp Pasta.webp" },
      { itemCode: "B10022", name: "Lemon Butter Pasta", price: 1950.00,discount: 0, img: "../assets/images/Pasta-Category/Lemon Butter Pasta.webp" },
      { itemCode: "B10023", name: "Tagliatelle Chicken Pasta", price: 2400.00,discount: 1, img: "../assets/images/Pasta-Category/Tagliatelle Pasta.png" },
      { itemCode: "B10024", name: "Baked Ravioli", price: 2000.00,discount: 1, img: "../assets/images/Pasta-Category/Baked Ravioli.webp" }
  ],
  "Fries": [
      { itemCode: "B10025", name: "Steak Fries", price: 1200.00,discount: 0, img: "../assets/images/Fries-Category/Steak Fries.png" },
      { itemCode: "B10026", name: "French Fries", price: 800.00,discount: 0, img: "../assets/images/Fries-Category/French Fries.webp" },
      { itemCode: "B10027", name: "Potato Fries", price: 600.00,discount: 0, img: "../assets/images/Fries-Category/Sweet Potato Fries.webp" }
  ],
  
  "Chicken":[
      { itemCode: "B10028", name: "Fried Chicken", price: 1200.00,discount: 0, img: "../assets/images/Chicken-Category/Fried Chicken.png" },
      { itemCode: "B10029", name: "BBQ Chicken", price: 2100.00,discount: 0, img: "../assets/images/Chicken-Category/BBQ Chicken.png" },
      { itemCode: "B10030", name: "Devilled Chicken", price: 900.00,discount: 0, img: "../assets/images/Chicken-Category/Devilled Chicken.webp" },
      { itemCode: "B10031", name: "Hot Wings", price: 2400.00,discount: 5, img: "../assets/images/Chicken-Category/Hot Wings.png" }
  ],
  "Beverages": [
      { itemCode: "B10032", name: "Pepsi (330ml)", price: 990.00,discount: 2, img: "../assets/images/Bevarages-Category/Pepsi.webp" },
      { itemCode: "B10033", name: "Coca-Cola (330ml)", price: 1230.00,discount: 0, img: "../assets/images/Bevarages-Category/Coca-Cola.webp" },
      { itemCode: "B10034", name: "Sprite (330ml)", price: 1500.00,discount: 3, img: "../assets/images/Bevarages-Category/Sprite.webp" },
      { itemCode: "B10035", name: "Mirinda (330ml)", price: 850.00,discount: 7, img: "../assets/images/Bevarages-Category/Mirinda.webp" }
  ]
  };

export const customerArray = [
  {
      customerID: 1,
      img: "../assets/images/man.png",
      firstName: "Saman",
      lastName: "Silva",
      occupation: "Software Engineer",
      gender: "Male",
      location: "Kandy",
      email: "saman@gmail.com",
      phoneNumber: "0776775195",
      additionalInfo: "",
  },
  {
      customerID: 2,
      img: "../assets/images/man.png",
      firstName: "Anura",
      lastName: "Perera",
      occupation: "Teacher",
      gender: "Male",
      location: "Colombo",
      email: "anura@gmail.com",
      phoneNumber: "0771234567",
      additionalInfo: "",
  },
  {
      customerID: 3,
      img: "../assets/images/girl.png",
      firstName: "Kumari",
      lastName: "Wijesinghe",
      occupation: "Doctor",
      gender: "Female",
      location: "Galle",
      email: "kumari.w@gmail.com",
      phoneNumber: "0779234561",
      additionalInfo: "",
  },
  {
      customerID: 4,
      img: "../assets/images/man.png",
      firstName: "Sarath",
      lastName: "Fernando",
      occupation: "Accountant",
      gender: "Male",
      location: "Negombo",
      email: "sarathf@gmail.com",
      phoneNumber: "0711123456",
      additionalInfo: "",
  },
  {
      customerID: 5,
      img: "../assets/images/girl.png",
      firstName: "Nadeesha",
      lastName: "Bandara",
      occupation: "Engineer",
      gender: "Female",
      location: "Kurunegala",
      email: "nadeesha.b@gmail.com",
      phoneNumber: "0784567890",
      additionalInfo: "",
  },
  {
      customerID: 6,
      img: "../assets/images/man.png",
      firstName: "Mahinda",
      lastName: "Ranasinghe",
      occupation: "Lawyer",
      gender: "Male",
      location: "Jaffna",
      email: "mahinda.r@gmail.com",
      phoneNumber: "0763456789",
      additionalInfo: "",
  },
  {
      customerID: 7,
      img: "../assets/images/girl.png",
      firstName: "Sanduni",
      lastName: "Jayasinghe",
      occupation: "Pharmacist",
      gender: "Female",
      location: "Matara",
      email: "sanduni.j@gmail.com",
      phoneNumber: "0745678910",
      additionalInfo: "",
  },
  {
    customerID: 8,
    img: "../assets/images/girl.png",
    firstName: "Chathurika",
    lastName: "Gunasekara",
    occupation: "Architect",
    gender: "Female",
    location: "Ratnapura",
    email: "chathurika.g@gmail.com",
    phoneNumber: "0713456789",
    additionalInfo: "",
  },
  {
      customerID: 9,
      img: "../assets/images/man.png",
      firstName: "Ruwan",
      lastName: "Dias",
      occupation: "Chef",
      gender: "Male",
      location: "Kalutara",
      email: "ruwan.d@gmail.com",
      phoneNumber: "0729876543",
      additionalInfo: "",
  },
  {
      customerID: 10,
      img: "../assets/images/man.png",
      firstName: "Tharindu",
      lastName: "Rajapaksha",
      occupation: "Graphic Designer",
      gender: "Male",
      location: "Gampaha",
      email: "tharindu.r@gmail.com",
      phoneNumber: "0775566778",
      additionalInfo: "",
  }
];
